services:
  db:
    image: postgres:15
    restart: always
    container_name: db_sneakers
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5445:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    tty: true
    stdin_open: true
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend_sneakers
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: backend_sneakers
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local